package dev.shadowsoffire.apotheosis.affix;

import dev.shadowsoffire.apotheosis.affix.effect.MagicalArrowAffix;
import dev.shadowsoffire.apotheosis.loot.LootCategory;
import dev.shadowsoffire.apotheosis.socket.SocketHelper;
import dev.shadowsoffire.apotheosis.util.PersistentDataComponent;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.projectile.Projectile;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.phys.HitResult;

/**
 * Port of upstream {@code AdventureEvents#fireProjectile} and {@code #impact} (NeoForge {@code EntityJoinLevelEvent} and
 * {@code ProjectileImpactEvent}). Called from {@code ServerLevelProjectileMixin} and {@code ProjectileImpactMixin}.
 */
public class ProjectileHooks {

    /** Marks a projectile generated by an affix (Spectral Shot), so it doesn't trigger the fire hook again. */
    public static final String GENERATED = "apoth.generated";
    /** Set on a projectile fired from a weapon with the Magical affix; read by {@code DamageSourceMagicalMixin}. */
    public static final String MAGICAL = "apoth.magical";

    /**
     * A freshly added projectile (never one loaded from disk) with a living owner copies the owner's weapon onto itself
     * and runs the weapon's affix and gem fire hooks.
     * <p>
     * The weapon is the arrow's own recorded weapon ({@link AbstractArrow#getWeaponItem()}, set by vanilla bows and
     * crossbows and by modded bows that pass it on), else upstream's choice: the owner's item in use, else the main hand
     * item if it's a ranged weapon (or, Gameoverse, a spell weapon), else the off hand item.
     */
    public static void onProjectileAdded(Projectile proj) {
        if (!(proj.getOwner() instanceof LivingEntity user)) return;
        if (PersistentDataComponent.get(proj).getBooleanOr(GENERATED, false)) return;

        ItemStack weapon = ItemStack.EMPTY;
        if (proj instanceof AbstractArrow arrow) {
            ItemStack w = arrow.getWeaponItem();
            if (w != null) weapon = w;
        }
        if (weapon.isEmpty()) {
            weapon = user.getUseItem();
        }
        if (weapon.isEmpty()) {
            weapon = user.getMainHandItem();
            if (weapon.isEmpty() || !firesProjectiles(LootCategory.forItem(weapon))) {
                weapon = user.getOffhandItem();
            }
        }
        if (weapon.isEmpty()) return;

        SocketHelper.getGems(weapon).onProjectileFired(user, proj);
        boolean[] magical = { false };
        ItemStack src = weapon;
        AffixHelper.streamAffixes(src).forEach(a -> {
            a.onProjectileFired(user, proj);
            if (a.getAffix() instanceof MagicalArrowAffix) magical[0] = true;
        });
        AffixHelper.copyToProjectile(weapon, proj);
        if (magical[0]) {
            PersistentDataComponent.get(proj).putBoolean(MAGICAL, true);
        }
    }

    /**
     * A projectile hit something (after deflection and Apothic dodge checks): runs the source weapon's gem and affix
     * impact hooks.
     */
    public static void onProjectileImpact(Projectile proj, HitResult res) {
        if (proj.level().isClientSide()) return;
        if (!PersistentDataComponent.get(proj).contains(AffixHelper.SOURCE_WEAPON)) return;
        SocketHelper.getGemInstances(proj).forEach(inst -> inst.onProjectileImpact(proj, res));
        AffixHelper.getAffixes(proj).values().forEach(inst -> {
            if (inst.isValid()) inst.onProjectileImpact(proj, res, res.getType());
        });
    }

    /** Upstream: ranged weapons. Gameoverse: spell weapons too, whose projectile spells carry the staff's affixes. */
    private static boolean firesProjectiles(LootCategory cat) {
        return cat.isRanged() || cat == dev.shadowsoffire.apotheosis.Apoth.LootCategories.SPELL_WEAPON;
    }

    public static boolean isMagical(AbstractArrow arrow) {
        return PersistentDataComponent.get(arrow).getBooleanOr(MAGICAL, false);
    }
}
